#pragma once
#include "CoreMinimal.h"
#include "EStatusEffectType.generated.h"

UENUM(BlueprintType)
enum class EStatusEffectType : uint8 {
    None,
    MoveSpeed,
    Immunity,
    MaxHealth,
    MaxStamina,
    MaxStun,
    StaminaSprint,
    StaminaAttack,
    SwimSpeed,
    MaxHauling,
    FallDamage,
    WaterBreathing,
    TeamChange,
    HungerRate,
    ThirstRate,
    StaminaRegenRate,
    DisableMovement,
    SpawnActor,
    WaterBreathingRate,
    AttackDamage,
    Health,
    Stamina,
    Food,
    Water,
    DamageReduction,
    CriticalHitChance,
    ReviveTime,
    ApplyAttackEffect,
    AllowAirbornStaminaRegen,
    PerfectBlockTime,
    ApplyBlockEffect,
    ReflectDamage,
    LifeSteal,
    Invisibility,
    Stun,
    TriggerExtraAttack,
    EquipmentDurability,
    StaminaCapMultiplier,
    DirtyWater,
    GliderDurabilityDrainMultiplier,
    AttackSpeed,
    Sizzle,
    StaminaDelay,
    SizzleRateMultiplier,
    ApplyBlockEffectSelf,
    TokenCooldownTime,
    AbilityCooldownMultiplier,
    ApplyCritEffect,
    ApplyCritEffectSelf,
    ThreatMultiplier,
    HealingReceived,
    AttackChargeTimeMultiplier,
    ExhaustionTimeMultiplier,
    SummonStatusEffect,
    ApplyKillEffect,
    CriticalDamage,
};

